version: "3.9"
services:
  backend:
    image: xoriax/family-backend:latest
    container_name: backend
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.routers.backend.service=backend"
      - "traefik.http.routers.backend.rule=Host(`api.labofdev.ru`)"
      - "traefik.http.services.backend.loadbalancer.server.port=4000"
    command: >
      sh -c " alembic upgrade head &&
              uvicorn api.main:app --port 4000 --host 0.0.0.0"
    environment:
      - SECRET_KEY=a)&tg!@-@liw2+v!_64!v1_o+2r%e3ufl#e!n*_ar5a$q=9n!p
      - postgresql+asyncpg://postgresql:postgresql@localhost:5432/family
    networks:
      - web
    ports:
      - "4000:4000"

  frontend:
    image: xoriax/family-frontend:latest
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.routers.frontend.rule=Host(`family.labofdev.ru`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    networks:
      - web
    ports:
      - "3000:3000"

networks:
  web:
    external: true
