"""add_finished_status

Revision ID: 31a6363a58a9
Revises: 7703478ba824
Create Date: 2024-06-06 11:34:41.377224

"""
from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '31a6363a58a9'
down_revision: str = '7703478ba824'
branch_labels: str | Sequence[str] | None = None
depends_on:  str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_finished', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'is_finished')
    # ### end Alembic commands ###
